#include "space.h"

/* 
Space Constructor
Description:
Simple Space constructor passes parameter values onto Radiosity solver.

Parameters: 
float fw: Cornell-Box Face width.
int hps: Cornell-Box Elements Per Face Side.

Output: -
 */
Space::Space(float fw, int hps):
r{fw,hps}
{
}

/* 
Color<int> Space::request_color(Ray ray, float tMin, float tMax)
Description:
Request Color to Space object, any rendering system can use this function to request color data to Radiosity solver.

Parameters: 
Ray ray: Ray generated by rendering system to get color data.
float tMin: Ray minimum collision testing boundary. 
float tMax: Ray maximum collision testing boundary. 

Output:
Color<int>: Color requested by rendering system.
 */
Color<int> Space::request_color(Ray ray, float tMin, float tMax)
{
    return r.get_color(ray, tMin, tMax);
}
